name: Flutter Build Workflow

on:
  pull_request:
    branches:
      - main  
  push:
    branches:
      - main

jobs:
  build:
    name: Flutter Web Build
    runs-on: ubuntu-latest

    steps:
        #Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      
        #Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  
          channel: 'stable'

        #Install Dependencies
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./app
      
        #Run Flutter Test
      - name: Run Tests
        run: flutter test
      
        #Build Web App
      - name: Build Application
        run: flutter build web  
